# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: RaspiCam

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Yarn
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Create archive folder
        run: mkdir archive
      - name: Create zip
        run: cd build && zip -r ../archive/raspiCam.zip * && cd -
      - name: Create tar.gz
        run: cd build && tar -zcf ../archive/raspiCam.tar.gz * && cd -
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: raspiCam
          path: archive
